export type Product={id:string;name:string;category:string;texture:string;lengths:number[];price:number;density:string;lace:string;cap:string;image:string;description:string;badge?:string};
export const products:Product[]=[
{id:"full-frontal-tiwa",name:"Full Frontal Tiwa",category:"Frontal Wigs",texture:"Straight",lengths:[0],price:25000,density:"N/A",lace:"Full Frontal",cap:"N/A",image:"/d-luxury-hair-collection/products/full-frontal-tiwa.jpg",description:"Full frontal Tiwa — 100% human hair factory wig.",badge:"100% HUMAN HAIR"},
{id:"frontal-body-human-hair-blend",name:"Frontal Body Human Hair Blend",category:"Frontal Wigs",texture:"Body Wave",lengths:[0],price:36000,density:"N/A",lace:"Frontal",cap:"N/A",image:"/d-luxury-hair-collection/products/frontal-body-human-hair-blend.jpg",description:"Frontal — 100% human hair, body human hair blend.",badge:"100% HUMAN HAIR"},
{id:"double-drawn-2-6-10in",name:"Double Drawn 2/6 Wig",category:"Wigs",texture:"Straight",lengths:[10],price:64000,density:"N/A",lace:"2/6",cap:"N/A",image:"/d-luxury-hair-collection/products/double-drawn-2-6-10in.jpg",description:"Double drawn 2/6 wig, 10 inches — 100% human hair factory wig.",badge:"100% HUMAN HAIR"},
{id:"imperial-bone-straight",name:"Imperial Bone Straight Wig",category:"Wigs",texture:"Bone Straight",lengths:[18,20,22,24],price:150000,density:"200%",lace:"5×5 HD Closure",cap:"Medium",image:"https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?auto=format&fit=crop&w=1000&q=85",description:"Silky, sleek and polished, this statement wig is designed for an effortlessly expensive finish.",badge:"BESTSELLER"},
{id:"royal-body-wave",name:"Royal Body Wave",category:"Wigs",texture:"Body Wave",lengths:[18,20,22,24,26],price:175000,density:"220%",lace:"13×4 HD Frontal",cap:"Medium",image:"https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1000&q=85",description:"Soft, luxurious waves with movement and volume for an elegant everyday glam look."},
{id:"regal-deep-wave",name:"Regal Deep Wave",category:"Deep Wave",texture:"Deep Wave",lengths:[18,20,22,24,26],price:185000,density:"220%",lace:"13×4 HD Frontal",cap:"Medium",image:"https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=1000&q=85",description:"Defined deep waves with a soft, full-bodied finish that keeps its luxurious texture."},
{id:"sovereign-curly",name:"Sovereign Curly Wig",category:"Curly Hair",texture:"Curly",lengths:[16,18,20,22],price:165000,density:"200%",lace:"5×5 HD Closure",cap:"Medium",image:"https://images.unsplash.com/photo-1620331311520-246422fd82f9?auto=format&fit=crop&w=1000&q=85",description:"Soft, defined curls crafted for a rich, glamorous silhouette with natural movement.",badge:"NEW"},
{id:"crown-raw-hair",name:"Crown Raw Human Hair",category:"Raw Hair",texture:"Straight",lengths:[18,20,22,24,26,28],price:220000,density:"N/A",lace:"N/A",cap:"N/A",image:"https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&w=1000&q=85",description:"Premium raw human hair selected for longevity, versatility and a naturally luxurious finish.",badge:"PREMIUM"},
{id:"signature-frontal",name:"Signature Frontal Wig",category:"Frontal Wigs",texture:"Body Wave",lengths:[18,20,22,24],price:195000,density:"200%",lace:"13×4 HD Frontal",cap:"Medium",image:"https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=1000&q=85",description:"A refined frontal wig with a natural hairline and polished body-wave texture."},
{id:"elegance-closure",name:"Elegance Closure Wig",category:"Closure Wigs",texture:"Bone Straight",lengths:[16,18,20,22],price:135000,density:"180%",lace:"5×5 HD Closure",cap:"Medium",image:"https://images.unsplash.com/photo-1534180477871-5d6cc81f3920?auto=format&fit=crop&w=1000&q=85",description:"An easy, elegant closure wig for a sleek luxury look without the fuss."},
{id:"luxe-custom-wig",name:"Luxe Custom Wig",category:"Custom Wigs",texture:"Custom",lengths:[16,18,20,22,24,26],price:250000,density:"250%",lace:"Custom",cap:"Custom",image:"https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1000&q=85",description:"Your vision, made personal. A custom-made luxury wig tailored to your preferred texture, length and fit."},
{id:"silk-bone-straight",name:"Silk Bone Straight Bundles",category:"Bone Straight",texture:"Bone Straight",lengths:[18,20,22,24,26,28],price:145000,density:"N/A",lace:"N/A",cap:"N/A",image:"https://images.unsplash.com/photo-1527799820374-dcf8e5f4c7d6?auto=format&fit=crop&w=1000&q=85",description:"Smooth, glossy bone-straight bundles with a clean finish for custom wig making."},
{id:"divine-body-wave",name:"Divine Body Wave Bundles",category:"Body Wave",texture:"Body Wave",lengths:[18,20,22,24,26],price:155000,density:"N/A",lace:"N/A",cap:"N/A",image:"https://images.unsplash.com/photo-1560869713-da86a9ec0744?auto=format&fit=crop&w=1000&q=85",description:"Classic soft waves that blend beautifully and hold their elegant pattern."}];
export const formatNaira=(value:number)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(value);
export const categories=["Wigs","Raw Hair","Frontal Wigs","Closure Wigs","Bone Straight","Curly Hair","Body Wave","Deep Wave","Custom Wigs"];
export const textures=["Bone Straight","Body Wave","Deep Wave","Curly","Straight","Custom"];
